#!/bin/bash --

function _error
{
	echo 1>&2 "${1}"
	exit ${2}
}

C_LIB=clib2
if (( ${#} > 0 ))
then
    if [[ "${1}" == "clib=newlib" ]]
    then
	C_LIB=newlib
    elif [[ "${1}" != "clib=clib2" ]]
    then
	_error "Could not understand argument ${1}. Only clib=<newlib|clib2[default]> is understood" 1
    fi
fi
INSTALL_PREFIX="$(pwd)/installAmiga_${C_LIB}"

which ppc-amigaos-gcc 1>/dev/null 2>&1 || _error "Expected ppc-amigaos cross compiler on the path" 10

function create_amiga_SDK_package
{
    SDK_DIRS=(
	"local/${C_LIB}/bin"
	"local/${C_LIB}/lib"
	"local/${C_LIB}/share/libjpeg/man"
	"local/${C_LIB}/share/libjpeg/doc"
	"local/common/include"
    )

    for sdk_dir in "${SDK_DIRS[@]}"
    do
	mkdir -p "${sdk_dir}"
	find "${INSTALL_PREFIX}" -type d -iname "$(basename ${sdk_dir})" -exec cp -r {}/. "${sdk_dir}" \;
    done
    lha a libjpeg_9e.lha local/
}

./configure \
    --prefix="${INSTALL_PREFIX}" \
    --enable-static \
    --disable-shared \
    --host=ppc-amigaos \
    CFLAGS="-mcrt=${C_LIB}" \
    CXXFLAGS="-mcrt=${C_LIB}" \
    CPPFLAGS="-mcrt=${C_LIB}" \
    LDFLAGS="-mcrt=${C_LIB}"
    
if (( !${?} ))
then
    { make -j$(nproc) && make install ; } || _error "Error with make" 2
    create_amiga_SDK_package
    echo "FINISHED. See libjpeg_9e.lha"
else
    _error "Error with configure" 3
fi
